services:
  api:
    container_name: api
    build:
      context: ./server
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 5000:5000
    networks:
      - app_network
  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

networks:
  app_network:
    external: false