/* istanbul ignore file */
import { Employee } from "../entities/employee";

export const employeesTestData = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 2,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 3,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 4,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 5,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 6,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 7,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 8,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 9,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 10,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 11,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 12,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 13,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 14,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 15,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 16,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 17,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 18,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 19,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
  {
    id: 20,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-555-5555",
    address: {
      firstLine: "Flat 123",
      street: "123 Main Street",
      city: "New York",
    },
  },
] as Employee[];
