import Head from "next/head";
import { gql } from "@apollo/client";
import { client } from "../../lib/apollo-client";

// @ts-ignore
export default function Home({ data }) {
  const { employees } = data;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {employees.slice(0, 10).map((employee: any) => {
          return (
            <div key={employee.id}>
              <h2>first name: {employee.firstName}</h2>
              <h2>last name: {employee.lastName}</h2>
              <h2>email: {employee.email}</h2>
              <h2>phone number: {employee.phoneNumber}</h2>
              <div>
                <h2>Address:</h2>
                <h2>{employee.address.firstLine}</h2>
                <h2>{employee.address.street}</h2>
                <h2>{employee.address.city}</h2>
              </div>
              <br />
            </div>
          );
        })}
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const employees = gql`
    query {
      employees {
        id
        firstName
        lastName
        email
        phoneNumber
        address {
          city
          firstLine
          street
        }
      }
    }
  `;

  const { data } = await client.query({ query: employees });

  return { props: { data } };
};
