import Head from "next/head";
import Header from "@Components/components/header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="w-screen h-screen p-10">
        <h1 className="text-3xl font-bold">
          Welcome to Nick Morgan's Technical test.
        </h1>
        <div className="flex gap-2 items-center py-5">
          <p className="text-xl">
            Please visit the employee's list page via the navigation bar under
            "Employees".
          </p>
        </div>
      </main>
    </>
  );
}
