import React from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import "../styles/global.css";

import ContextProvider from "./Context/apollo-provider";

export default function RootLayout({ children }) {
  return (
    <ContextProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ContextProvider>
  );
}
