import styled from '@emotion/styled'
import Head from 'next/head'
import Button from '../components/Button/Button'
import SkeletonLoader from '../components/Skeleton/Skeleton'
import UserCard from '../components/UserCard/UserCard'

const Home = () => {

  return (
    <div>
      <Head>
        <title>Users App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainWrapper>
        <Grid>
          <UserCard/>
          <UserCard/>
          <UserCard/>
          <UserCard/>
          <UserCard/>
          <UserCard/>
          <SkeletonLoader/>
        </Grid>
        <Button/>
      </MainWrapper>
    </div>
  )
}

export default Home

const MainWrapper = styled.main`
display: flex;
flex-direction:column;
justify-content: center;
align-items: center;
margin-top: 3rem;
`;

const Grid = styled.div`
display: grid;
grid-template-rows: auto;
grid-row-gap: 15px;
width: 60%;

@media screen and (max-width:680px){
  margin:auto;
  display: grid;
  grid-template-columns: repeat(1, 100%);
  width: 80%;
  font-size: var(--font-size-p-small);
}
`