FROM node:18

ENV PORT 4000

# Create app directory
RUN mkdir -p /home/app/server/ && chown -R node:node /home/app/server
WORKDIR /home/app/server
COPY --chown=node:node . .

USER node

RUN yarn install

EXPOSE 4000

CMD ["yarn", "start"]